ALTER TABLE "tournaments" ADD COLUMN IF NOT EXISTS "raceTo" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "tournament_matches" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3);
ALTER TABLE "tournament_matches" ADD COLUMN IF NOT EXISTS "tableId" TEXT;
