import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, StyleSheet, ActivityIndicator, TouchableOpacity } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../../context/AuthContext';
import { COLORS, RANK_CONFIG } from '../../constants';

export default function PlayerProfileScreen({ route, navigation }: any) {
  const [player, setPlayer] = useState<any>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { api.get(`/api/users/public/${route.params.userId}`).then((res) => setPlayer(res.data)).finally(() => setLoading(false)); }, [route.params.userId]);
  if (loading) return <View style={s.center}><ActivityIndicator size="large" color={COLORS.primary}/></View>;
  if (!player) return <View style={s.center}><Text style={s.muted}>Player profile unavailable.</Text></View>;
  const gp = player.gamifiedProfile || {}; const rank = gp.rank || 'Rookie'; const config = RANK_CONFIG[rank as keyof typeof RANK_CONFIG] || RANK_CONFIG.Rookie;
  return <ScrollView style={s.container} contentContainerStyle={s.content}><View style={s.header}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={24} color={COLORS.textPrimary}/></TouchableOpacity><Text style={s.headerTitle}>Player Profile</Text><View style={{width:24}}/></View>
    <View style={[s.hero,{borderColor:config.color+'80'}]}><View style={[s.avatar,{backgroundColor:config.color+'20',borderColor:config.color}]}>{player.avatarUrl ? null : <Text style={s.avatarText}>{config.icon}</Text>}</View><Text style={s.name}>{gp.displayName || `${player.firstName} ${player.lastName}`}</Text><Text style={[s.rank,{color:config.color}]}>{rank} · Level {gp.level || 1}</Text>{player.membership?.status && <Text style={s.member}>{player.membership.plan || 'Member'} · {player.membership.status}</Text>}</View>
    <View style={s.stats}>{[['trophy-outline','Tournament wins',player.tournamentWins],['people-outline','Tournaments joined',player.tournamentsJoined],['trending-up-outline','Match wins',gp.totalWins || 0],['trending-down-outline','Match losses',gp.totalLosses || 0]].map(([icon,label,value])=><View key={String(label)} style={s.stat}><Ionicons name={icon as any} size={18} color={COLORS.primary}/><Text style={s.statValue}>{String(value)}</Text><Text style={s.statLabel}>{String(label)}</Text></View>)}</View>
    <View style={s.card}><Text style={s.title}>Achievements & Titles</Text>{player.championTitles?.length ? player.championTitles.map((title:any)=><View key={`${title.tournamentName}-${title.earnedAt}`} style={s.titleRow}><Ionicons name="trophy" size={20} color={COLORS.gold}/><View style={{flex:1}}><Text style={s.titleName}>{title.tournamentName} Champion</Text><Text style={s.muted}>{title.format?.replace(/_/g,' ')} · Earned {new Date(title.earnedAt).toLocaleDateString('en-PH')}</Text></View></View>) : <Text style={s.muted}>No tournament titles earned yet.</Text>}{gp.badges?.length ? <View style={s.badges}>{gp.badges.map((badge:string)=><View key={badge} style={s.badge}><Text style={s.badgeText}>{badge.replace(/_/g,' ')}</Text></View>)}</View> : null}</View>
    <Text style={s.joined}>Member since {new Date(player.createdAt).toLocaleDateString('en-PH', {month:'long', year:'numeric'})}</Text>
  </ScrollView>;
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},content:{padding:16,gap:15,paddingBottom:30},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:COLORS.background},header:{paddingTop:45,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},headerTitle:{color:COLORS.textPrimary,fontWeight:'800',fontSize:18},hero:{alignItems:'center',gap:7,padding:20,backgroundColor:COLORS.surface,borderWidth:1,borderRadius:18},avatar:{width:82,height:82,borderRadius:41,borderWidth:2,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:38},name:{color:COLORS.textPrimary,fontWeight:'800',fontSize:22},rank:{fontWeight:'800'},member:{color:COLORS.textSecondary,fontSize:12},stats:{flexDirection:'row',flexWrap:'wrap',gap:9},stat:{width:'48.5%',backgroundColor:COLORS.surface,borderColor:COLORS.surfaceBorder,borderWidth:1,borderRadius:13,padding:13,gap:3},statValue:{color:COLORS.textPrimary,fontWeight:'800',fontSize:19},statLabel:{color:COLORS.textMuted,fontSize:11},card:{backgroundColor:COLORS.surface,borderColor:COLORS.surfaceBorder,borderWidth:1,borderRadius:15,padding:15,gap:12},title:{fontSize:16,fontWeight:'800',color:COLORS.textPrimary},titleRow:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:8,borderTopWidth:1,borderColor:COLORS.surfaceBorder},titleName:{color:COLORS.textPrimary,fontWeight:'700'},muted:{color:COLORS.textMuted,fontSize:12},badges:{flexDirection:'row',flexWrap:'wrap',gap:7},badge:{backgroundColor:COLORS.primary+'18',borderRadius:9,paddingHorizontal:9,paddingVertical:6},badgeText:{color:COLORS.primary,fontWeight:'700',fontSize:11},joined:{textAlign:'center',color:COLORS.textMuted,fontSize:12}});
